name: arponr
url: http://www.arponr.com

markdown: Kramdown

permalink: pretty

exclude: ["publish.sh"]
excerpt_separator: ""

paginate: 10
paginate_path: ":num"

nav_tags:
- all
- math
- reading
- writing



