name: arponr
url: http://web.stanford.edu/~arpon/writing
baseurl: /~arpon/writing

markdown: Kramdown

permalink: pretty

exclude: ["publish.sh"]
excerpt_separator: ""

sections:
- art
- analysis




